#ifndef _E2K_ASM_CPU_FEATURES_H
#define _E2K_ASM_CPU_FEATURES_H

#ifndef __ASSEMBLY__
enum {
	/* Hardware bugs */
	CPU_HWBUG_LARGE_PAGES,
	CPU_HWBUG_LAPIC_TIMER,
	CPU_HWBUG_PIO_READS,
	CPU_HWBUG_ATOMIC,
	CPU_HWBUG_CLW,
	CPU_HWBUG_PAGE_A,
	CPU_HWBUG_SPURIOUS_EXC_ILL_INSTR_ADDR,
	CPU_HWBUG_UNALIGNED_LOADS,
	CPU_HWBUG_CANNOT_DO_DMA_IN_NEIGHBOUR_NODE,
	CPU_HWBUG_DMA_AT_APIC_ADDR,
	CPU_HWBUG_KERNEL_DATA_MONITOR,
	CPU_HWBUG_WRITE_MEMORY_BARRIER,
	CPU_HWBUG_BAD_RESET,
	CPU_HWBUG_BREAKPOINT_INSTR,
	CPU_HWBUG_E8C_WATCHDOG,
	CPU_HWBUG_IOMMU,
	CPU_HWBUG_WC_DAM,
	CPU_HWBUG_TRAP_CELLAR_S_F,
	CPU_HWBUG_SS,
	CPU_HWBUG_AAU_AALDV,
	CPU_HWBUG_LEVEL_EOI,
	CPU_HWBUG_FALSE_SS,
	CPU_HWBUG_SPURIOUS_EXC_DATA_DEBUG,
	CPU_HWBUG_TLB_FLUSH_L1D,
	CPU_HWBUG_GUEST_ASYNC_PM,
	CPU_HWBUG_E16C_SLEEP,
	CPU_HWBUG_L1I_STOPS_WORKING,
	CPU_HWBUG_CLW_STALE_L1_ENTRY,
	CPU_HWBUG_PIPELINE_FREEZE_MONITORS,
	CPU_HWBUG_C3_WAIT_MA_C,
	CPU_HWBUG_VIRT_SCLKM3_INTC,
	CPU_HWBUG_VIRT_PUSD_PSL,
	CPU_HWBUG_USD_ALIGNMENT,
	CPU_HWBUG_VIRT_PSIZE_INTERCEPTION,
	CPU_NO_HWBUG_SOFT_WAIT,
	CPU_HWBUG_SOFT_WAIT_E8C2,
	CPU_HWBUG_C3,

	/* Features, not bugs */
	CPU_FEAT_WC_PCI_PREFETCH,
	CPU_FEAT_FLUSH_DC_IC,
	CPU_FEAT_EPIC,
	CPU_FEAT_TRAP_V5,
	CPU_FEAT_TRAP_V6,
	CPU_FEAT_QPREG,
	CPU_FEAT_HW_PREFETCHER,
	CPU_FEAT_SEPARATE_TLU_CACHE,
	CPU_FEAT_FILLR,
	CPU_FEAT_FILLC,
	CPU_FEAT_ISET_V3,
	CPU_FEAT_ISET_V5,
	CPU_FEAT_ISET_V6,

	NR_CPU_FEATURES
};
#endif

#endif
