#ifndef _ASM_E1CP_H_
#define _ASM_E1CP_H_

/*
 * Machine (based on E1C+ processor) topology:
 * E1C+ is one core CPU + graphical processor to support 3D, so
 * - is not NUMA system
 * - is not SMP system
 */

#ifndef __ASSEMBLY__
extern void boot_e1cp_setup_arch(void);
extern void e1cp_setup_machine(void);
#endif

#define	E1CP_CPU_VENDOR			ES2_CPU_VENDOR
#define	E1CP_CPU_FAMILY			ES2_CPU_FAMILY

#define E1CP_NR_NODE_CPUS		1
#define E1CP_MAX_NR_NODE_CPUS		E1CP_NR_NODE_CPUS

#define	E1CP_NODE_IOLINKS		2

#define	E1CP_PCICFG_AREA_PHYS_BASE	0x000000ff10000000UL
#define	E1CP_PCICFG_AREA_SIZE		0x0000000010000000UL

#define	E1CP_NBSR_AREA_OFFSET		E2S_NBSR_AREA_OFFSET
#define	E1CP_NBSR_AREA_SIZE		E2S_NBSR_AREA_SIZE

#define E1CP_MLT_SIZE			ES2_MLT_SIZE

#define	E1CP_TLB_LINES_BITS_NUM		ES2_TLB_LINES_BITS_NUM
#define E1CP_TLB_ADDR_LINE_NUM		E2S_TLB_ADDR_LINE_NUM
#define E1CP_TLB_ADDR_LINE_NUM2		E2S_TLB_ADDR_LINE_NUM2
#define E1CP_TLB_ADDR_LINE_NUM_SHIFT2	E2S_TLB_ADDR_LINE_NUM_SHIFT2
#define E1CP_TLB_ADDR_SET_NUM		E2S_TLB_ADDR_SET_NUM
#define E1CP_TLB_ADDR_SET_NUM_SHIFT	E2S_TLB_ADDR_SET_NUM_SHIFT

#define E1CP_SIC_MC_COUNT		ES2_SIC_MC_COUNT
#define E1CP_SIC_MC1_ECC		E2S_SIC_MC1_ECC

#define E1CP_CLOCK_TICK_RATE		ES2_CLOCK_TICK_RATE

#define E1CP_L1_CACHE_SHIFT		ES2_L1_CACHE_SHIFT
#define E1CP_L1_CACHE_BYTES		ES2_L1_CACHE_BYTES
#define E1CP_L2_CACHE_SHIFT		ES2_L2_CACHE_SHIFT
#define E1CP_L2_CACHE_BYTES		ES2_L2_CACHE_BYTES

#endif /* _ASM_E1CP_H_ */
