### generic

generic-y += bugs.h
generic-y += div64.h
generic-y += errno.h
generic-y += emergency-restart.h
generic-y += irq_regs.h
generic-y += kmap_types.h
generic-y += local64.h
generic-y += mcs_spinlock.h
generic-y += mm-arch-hooks.h
generic-y += preempt.h
generic-y += qrwlock.h
generic-y += xor.h
generic-y += mmiowb.h
